// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using NUnit.Framework.Internal.Execution;

namespace Note_pad
{
    [TestFixture]
    public class AuthCreateEditDeleteLogoutTest: TestBase {
        [Test]
        public void Auth() {
            manager.Navigation.OpenHomePage();
            AccountData user = new AccountData("Boooo211@yandex.ru", "12345678");
            manager.Auth.Authorization(user);
            var authorizedLogin = manager.Auth.GetAuthorizedLogin();
            Assert.AreEqual(user.Username, authorizedLogin);
            manager.Auth.Logout();
        }
        [Test]
        public void AuthAndCreate()
        {
            manager.Navigation.OpenHomePage();
            AccountData user = new AccountData("Boooo211@yandex.ru", "12345678");
            manager.Auth.Authorization(user);
            var authorizedLogin = manager.Auth.GetAuthorizedLogin();
            Assert.AreEqual(user.Username, authorizedLogin);
            manager.Notes.CreateNewNote();
            manager.Navigation.OpenHomePage();
            manager.Auth.Logout();
        }

        [Test]
        public void AuthCreateEditRemoveLogout()
        {
            manager.Navigation.OpenHomePage();
            AccountData user = new AccountData("Boooo211@yandex.ru", "12345678");
            manager.Auth.Authorization(user);
            var authorizedLogin = manager.Auth.GetAuthorizedLogin();
            Assert.AreEqual(user.Username, authorizedLogin);
            manager.Notes.CreateNewNote();
            NoteData note = new NoteData("New note created");
            manager.Notes.RenameNote(note);
            var assertNote = manager.Notes.GetRenamedNoteData();
            Assert.AreEqual(note.Name, assertNote.Name);
            manager.Notes.DeleteNote();
            manager.Auth.Logout();
        }
    }    
}
