// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using NUnit.Framework.Internal.Execution;

namespace Note_pad
{
    [TestFixture]
    public class AuthCreateEditDeleteLogoutTest: TestBase {
        [Test]
        public void Auth() {
            OpenHomePage();
            AccountData user = new AccountData("Boooo211@yandex.ru", "12345678");
            Authorization(user);
        }
        [Test]
        public void AuthAndCreate()
        {
            OpenHomePage();
            AccountData user = new AccountData("Boooo211@yandex.ru", "12345678");
            Authorization(user);
            Thread.Sleep(3000);
            CreateNewNote();
        }

        [Test]
        public void AuthCreateEditRemoveLogout()
        {
            OpenHomePage();
            AccountData user = new AccountData("Boooo211@yandex.ru", "12345678");
            Authorization(user);
            Thread.Sleep(3000);
            CreateNewNote();
            Thread.Sleep(3000);
            NoteData note = new NoteData("New note created");
            RenameNote(note);
            Thread.Sleep(3000);
            DeleteNote();
            Thread.Sleep(2000);
            Logout();
        }

        private void Logout()
        {
            driver.FindElement(By.LinkText("Выйти")).Click();
        }

        private void DeleteNote()
        {
            driver.FindElement(By.CssSelector(".icon_menu")).Click();
            Thread.Sleep(2000);
            driver.FindElement(By.CssSelector(".icon_delete")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.CssSelector("button.ui-button:nth-child(1) > span:nth-child(1)")).Click();
        }

        private void RenameNote(NoteData note)
        {
            driver.FindElement(By.CssSelector(".icon_menu")).Click();
            driver.FindElement(By.LinkText("Параметры")).Click();
            Thread.Sleep(3000);
            driver.FindElement(By.Id("title")).Click();
            driver.FindElement(By.Id("title")).SendKeys(note.Name);
            driver.FindElement(By.CssSelector("input:nth-child(18)")).Click();
        }

        private void CreateNewNote()
        {
            driver.FindElement(By.LinkText("+")).Click();
        }

        private void Authorization(AccountData user)
        {
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys(user.Username);
            driver.FindElement(By.Id("password")).Click();
            driver.FindElement(By.Id("password")).SendKeys(user.Password);
            driver.FindElement(By.CssSelector("tr:nth-child(3) input")).Click();
        }

        private void OpenHomePage()
        {
            driver.Navigate().GoToUrl("https://note-pad.net/");
            driver.Manage().Window.Size = new System.Drawing.Size(1440, 900);
        }
    }    
}
